const customerData = [
    {
        id: 1,
        cname: 'Metals Planet',
        email: 'info@metalsplanet.com',
        contact: 9879456329,
        location:'Delhi Gurgaon',
        role: 'buyer',
        comname: 'Metals Planet',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    },


    {
        id: 2,
        cname: 'Tata Steel',
        email: 'info@tatasteel.com',
        contact: 9898989898,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Tata Steel',
        quality: 'Q2',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: true
    },
    {
        id: 3,
        cname: 'Jindal Steel',
        email: 'info@jindalsteel.com',
        contact: 6565676752,
        location:'Delhi Gurgaon',
        role: 'buyer',
        comname: 'Jindal Steel',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    },
    {
        id: 4,
        cname: 'Lion Steel',
        email: 'info@lion.com',
        contact: 9428651846,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Lion Steel',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: true
    },
    {
        id: 5,
        cname: 'Alang Steel',
        email: 'info@alang.com',
        contact: 9898989898,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Alang Steel',
        quality: 'Q2',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    },
    {
        id: 6,
        cname: 'Metals Planet',
        email: 'info@metalsplanet.com',
        contact: 9879456329,
        location:'Delhi Gurgaon',
        role: 'buyer',
        comname: 'Metals Planet',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    },


    {
        id: 7,
        cname: 'Tata Steel',
        email: 'info@tatasteel.com',
        contact: 9898989898,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Tata Steel',
        quality: 'Q2',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: true
    },
    {
        id: 8,
        cname: 'Jindal Steel',
        email: 'info@jindalsteel.com',
        contact: 6565676752,
        location:'Delhi Gurgaon',
        role: 'buyer',
        comname: 'Jindal Steel',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    },
    {
        id: 9,
        cname: 'Lion Steel',
        email: 'info@lion.com',
        contact: 9428651846,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Lion Steel',
        quality: 'Q1',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: true
    },
    {
        id: 10,
        cname: 'Alang Steel',
        email: 'info@alang.com',
        contact: 9898989898,
        location:'Delhi Gurgaon',
        role: 'seller',
        comname: 'Alang Steel',
        quality: 'Q2',
        address: 'D South Block, Delhi Gurgaon',
        gst: 'DHGCFH658956BM',
        desigination: 'HR Manager',
        workPhone: 9556431411,
        status: false
    }];
export { customerData };